target_sources(ninfer_ops PRIVATE
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/causal_softmax_attention.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w1_h24_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w1_h24_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w1_h16_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w1_h16_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w2_h24_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w2_h24_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w2_h16_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w2_h16_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w3_h24_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w3_h24_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w3_h16_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w3_h16_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w4_h24_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w4_h24_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w4_h16_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w4_h16_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w5_h24_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w5_h24_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w5_h16_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w5_h16_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w6_h24_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w6_h24_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w6_h16_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w6_h16_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w7_h24_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w7_h24_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w8_h24_append.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_i8_w8_h24_cached.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_fp8.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_nvfp4.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/small_t_k8v4.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/prompt.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/prompt_fp8.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/prompt_nvfp4.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/prompt_k8v4.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/packed/packed_softmax_attention.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/dense/packed/launch.cu"
  "${CMAKE_CURRENT_LIST_DIR}/dense/context/context_softmax_attention.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/dense/context/launch.cu"
  "${CMAKE_CURRENT_LIST_DIR}/sliding_window/sliding_window_attention.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/sliding_window/launch.cu"
)

# The fast NVFP4 prompt kernel runs QK on block-scaled FP4 Tensor Cores (kind::mxf4nvf4), which
# only Blackwell has.
if(CMAKE_CUDA_ARCHITECTURES STREQUAL "120a")
  target_sources(ninfer_ops PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/dense/causal_cache/prompt_nvfp4_fast.cu")
endif()
